server:
  port: 0
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
  cloud:
    gateway:
      mvc:
        routes:
          #Product service
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/product # the link will be: http://localhost:8080/api/product
          #Order service
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/order # the link will be: http://localhost:8080/api/order
          #Inventory service
          - id: inventory-service
            uri: lb://inventory-service
            predicates:
              - Path=/api/inventory # the link will be: http://localhost:8080/api/inventory
          #Discovery service
          - id: discovery-service
            uri: http://localhost:8761/
            predicates:
              - Path=/eureka/web # the link will be: http://localhost:8080/eureka/web
            filters:
              - name: setPath=/

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: trace
