spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/inventory
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service

server:
  port: 0